# Generated by Django 4.0.2 on 2022-03-31 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_books',
        ),
    ]
