# Generated by Django 4.0.2 on 2022-03-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_favorite_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_authors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorite_genres',
        ),
    ]
