# Generated by Django 4.0.2 on 2022-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_genre_slug'),
        ('accounts', '0007_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='favoriteGenres',
            field=models.ManyToManyField(blank=True, to='library.Genre'),
        ),
    ]
