# Generated by Django 4.0.2 on 2022-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_genre_slug'),
        ('accounts', '0008_remove_user_user_id_user_favoritegenres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favoriteAuthors',
            field=models.ManyToManyField(blank=True, to='library.Author'),
        ),
    ]
