# Generated by Django 4.0.2 on 2022-03-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_sharedbook'),
        ('accounts', '0009_user_favoriteauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, to='library.Book'),
        ),
    ]
