# Generated by Django 4.0.2 on 2022-04-06 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
