# Generated by Django 4.0.2 on 2022-04-06 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_follow_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
