# Generated by Django 4.0.2 on 2022-04-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_message_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
