# Generated by Django 4.0.2 on 2022-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
