# Generated by Django 4.0.2 on 2022-04-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
